### ISSUE TITLE
Show the author field.

### ISSUE THREAD

**Issue by petersulucz** [deuxmoto/catilyfe-frontend#3]
There is a field in the UI which shows the author. The lovely backend/frontend returns said author. The UI ignores it serves up "SOMEBODY".
This needs to be addressed immediately, as our users are confused.
![somebody](https://user-images.githubusercontent.com/7218800/35002312-1c3f6a44-fa9e-11e7-8998-6eac09085c17.PNG)

**Comment by justaniles** [comment]
UGH using "Someone" keeps the users on their toes. They have to determine the author via their writing style

**Comment by petersulucz** [comment]
Yea, but my writin styl is 22222 goood
